ConfigMap: 
  stmt: 
    here: to setting enviromental varible please look below for that one of the popular example mysql databaser url configuration
  actual-url:
    here:  jdbc:mysql://localhost:3306/pickfresh?allowPublicKeyRetrieval=true&&useSSL=false
  modified-kubernates-with-enabled-enviromental-varible:
    here:  jdbc:mysql://${DB_HOST}/${DB_NAME}allowPublicKeyRetrieval=true&&useSSL=false

configMap-Syntax-here:
  cmd: 
    -  apiVersion: v1
       Kind: ConfigMap
       metadata:
         name: db-config
       data:
         host: mysql   # DB_HOST
         name: test    # DB_NAME
         
file-exexute-Command:
  cmd: kubectl apply -f filename
through-cmd-create-configMap:
  cmd:  kubectl create configmap configmap-name --from-literal=HOST=mysql  --from-literal=NAME=test