Deployment:
    deployment-describe:
      cmd: kubectl describe deployment deployment-name
    deployment-lists:
      cmd: kubectl get  deployments
    deployment-specific-deployment:
      cmd: kubectl get  deployment deployment-name
    deployment-append-to-file:
     cmd:  kubectl get  deployment deployment-name -o yaml >> filename(deployment.yml)
    deployment-delete:
     cmd: kubectl delete deployment deployment-name
    deployment-create-all-type-pods(and)replicas-also-automatically-see-that:
     cmd: kubectl get all
    deployment-syntax:
      cmd: 
        - apiVersion: apps/v1
        - Kind: Deployment
        - metadata:
           name: application
           lables:
             app: application
             tier : deployment
        - spec:
            replicas: 2
            selector:
             matchLabels:
              tier: end
            template:
              metadata:
                name: application
                lables:
                  app: application
                  tier: end
            spec:
              containers: 
                - name: redis
                  image: redis
    file-exexute-Command:
      cmd: kubectl apply -f filename